# Generated by Django 5.2.8 on 2025-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
